apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: api-dev-user-full-access
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
# - apiGroups: ["batch"]
#   resources:
#   - jobs
#   - cronjobs
#   verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: api-dev-user-full-access
  namespace: api
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: api-dev-user-full-access # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
subjects:
# You can specify more than one "subject"
- kind: Group
  name: 9233d3c8-063e-47be-b4e9-c79418f1f639 # "name" is case sensitive
  namespace: api